#ifndef SOCKIO_H
#define SOCKIO_H


#define CLIENT_TIMEOUT_CON_SEC 3
#define CLIENT_TIMEOUT_CON_USEC 1

#define CLIENT_TIMEOUT_DATA_SEC 3
#define CLIENT_TIMEOUT_DATA_USEC 1

#define SERVER_TIMEOUT_CON_SEC 3
#define SERVER_TIMEOUT_CON_USEC 1

#define SERVER_DROP_CHUNK_TIMEOUT_SEC 20
#define SERVER_DROP_CHUNK_TIMEOUT_USEC 0

#define SERVER_TIMEOUT_DATA_SEC 3
#define SERVER_TIMEOUT_DATA_USEC 1

typedef long unsigned int int_pair[2];
typedef unsigned char* buff_triple[3];

#define SERVER_DATA_TIMES_PAIR ((int_pair)){SERVER_TIMEOUT_DATA_SEC,SERVER_TIMEOUT_DATA_USEC}
#define CLIENT_DATA_TIMES_PAIR ((int_pair){CLIENT_TIMEOUT_DATA_SEC,CLIENT_TIMEOUT_DATA_USEC})

#define CLIENT_CON_TIMES_PAIR ((int_pair){CLIENT_TIMEOUT_CON_SEC,CLIENT_TIMEOUT_CON_USEC})

#define SERVER_DROP_CHUNK_TIMES_PAIR ((int_pair){SERVER_DROP_CHUNK_TIMEOUT_SEC,SERVER_DROP_CHUNK_TIMEOUT_USEC})




#endif
